### ISSUE TITLE
TypeScript: Find references / syntax highlighting breaks with dollar in member name

### ISSUE THREAD

**Issue by SimonHounsell** [kisstkondoros/typelens#47] opened 2019-11-26 11:17 UTC
Issue Type: <b>Bug</b>

Find references / syntax highlighting appears to be broken for members that contain a dollar sign in their name in TypeScript files.

![image](https://user-images.githubusercontent.com/37800313/69625153-e63c9180-103d-11ea-8aa9-948bdb95fddc.png)

In the above screenshot, you can't see the line of code that references `this.selectedDevelopmentChanged$` but I can assure you it's there. If I rename the field to `selectedDevelopmentChanged` (without the dollar), then it correctly shows the reference and syntax highlighting behaves as expected.

Adding `typescript` to the `typelens.skiplanguages` setting reinstates syntax highlighting.

Extension version: 1.9.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (8 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisstkondoros** [comment] 2019-12-08 23:58
I can't reproduce the issue locally.
Please attach a complete code example.

I'll close this, until further information is provided.

**Comment by SimonHounsell** [comment] 2019-12-09 14:31
> Please attach a complete code example.
```Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
Clear-Host

$DefaultUser = "s.hounsell"
$HartsCoreDir = "D:\Dev\repos\HartsCore\InfoTrack.Harts.Core"
$CoreProjectPath = "$HartsCoreDir\InfoTrack.Harts.Core.csproj"

function EditProfile { code $profile }
function reload { . $PROFILE }
function repos { Set-Location -Path D:\Dev\repos }
function a { Set-Location -Path D:\Dev\repos\Automation }
function f { Set-Location -Path D:\Dev\repos\ForWard }
function hc { Set-Location -Path $HartsCoreDir }
function hf { Set-Location -Path D:\Dev\repos\HartsFrontEnd }
function hi { Set-Location -Path D:\Dev\repos\HartsInfrastructure }
function hl { Set-Location -Path D:\Dev\repos\HartsLambda }
function hs { Set-Location -Path D:\Dev\repos\HartsSync\InfoTrack.Harts.Sync }
function Core-Run {
    dotnet build $CoreProjectPath
    dotnet run --project $HartsCoreDir
}
function Core-Update { dotnet ef database update --context HartsCoreContext --project $HartsCoreDir }
function Core-Pull {
    $CurrentLocation = Get-Location
    Set-Location $HartsCoreDir
    git checkout develop
    git pull
    git clean -fdx
    Set-Location $CurrentLocation
}
function Core-PullAndUpdate {
    Core-Pull
    Core-Update
}
function Core-PullUpdateRun {
    Core-PullAndUpdate
    Core-Run
}
function Core-MergeLatest {
    # Logically:
    # 1. Check it's a valid git directory
    # 2. Check it's not the develop or master branches
    # 3. Stash changes if there are any
    # 4. Checkout develop
    # 5. PullAndUpdateCore
    # 6. Checkout the starting branch
    # 7. Merge develop into the current branch
    #   a. Could get merge conflicts at this stage
    # 8. Unstash changes if there were any stashed at step 3
    #   a. Could get merge conflicts at this stage
    # 9. Switch back to the starting directory

    $ErrorActionPreference = "Stop"

    $CurrentLocation = Get-Location

    Set-Location $HartsCoreDir

    $GitBranch = cmd /c git branch --show-current '2>nul'
    if (!$GitBranch) {
        Write-Error "Current directory is not a git directory."
    }

    if ($GitBranch -Eq "master" -Or $GitBranch -Eq "develop") {
        Write-Error "Cannot merge develop when checked out branch is either master or develop. Current checked out branch is $GitBranch."
    }

    $GitStatus = git status -s

    if ($GitStatus) {
        git stash
        Write-Output "Stashed changes"
    }

    Core-PullAndUpdate

    git checkout $GitBranch

    git merge develop

    if ($GitStatus) {
        git stash pop
        Write-Output "Unstashed changes"
    }

    Set-Location $CurrentLocation
}
```

**Comment by kisstkondoros** [comment] 2019-12-09 14:55
In which universe is this typescript? :smiley:

**Comment by SimonHounsell** [comment] 2019-12-09 15:21
Sorry! It's not! Trying to do too many things at once!!!

**Comment by kisstkondoros** [comment] 2019-12-09 15:24
No worries, take your time :+1:

**Comment by SimonHounsell** [comment] 2019-12-11 15:40
> Please attach a complete code example.
```
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DataStoreService, DataStoreObject } from '../../data-store';
import { BaseFilesExplorerComponent } from '../base-files-explorer.component';
import { DocumentMetadata } from 'src/app/models';
import { NewBuildLayersService } from 'src/app/new-build/new-build-layers.service';
import { takeUntil, tap } from 'rxjs/operators';
import { of } from 'rxjs';

@Component({
  selector: 'harts-paged-files-explorer',
  templateUrl: './paged-files-explorer.component.html',
  styleUrls: ['./paged-files-explorer.component.scss']
})
export class PagedFilesExplorerComponent extends BaseFilesExplorerComponent implements OnInit {

  /** The title to name the component */
  @Input() public title: string;

  /** The number of items on a page */
  public pageSize = 3;

  /** The current page */
  public page = 0;

  private selectedDevelopmentChanged$ = this.newBuildLayersService.developmentsLayer.selectedDevelopmentChange
    .pipe(
      takeUntil(this.destroyed$),
      tap(_ => this.page = 0)
    );

  constructor(
    protected dataStore: DataStoreService,
    protected router: Router,
    protected newBuildLayersService: NewBuildLayersService) {
    super(dataStore, router);
  }


  /** Whether to allow upload from this control */
  @Input() canUpload = true;

  /** Whether to allow deletion from this control */
  @Input() canDelete = of(true);

  /** Processes document deletion, override base so not to change the route */
  public deleteDocument(document: DataStoreObject<DocumentMetadata>): void {
    this.dataStore.delete(document)
      .subscribe();

    this.selectedDocument = null;
  }

  /**
   * Executes when the component is initialized
   */
  public ngOnInit(): void {
    this.selectedDevelopmentChanged$.subscribe();

    const component = this;
    this.dropOptions = {
      allowDrop: (dragData: any) => {
        return this.canUpload ? component.isValidFileList(dragData) : false;
      }
    };
  }
}
```

**Comment by kisstkondoros** [comment] 2019-12-11 16:00
Thanks for providing the code!
For me it still shows it as used (no grayout)

![image](https://user-images.githubusercontent.com/14231157/70637369-674b7980-1c37-11ea-9550-3a68948e8d40.png)

I'm clueless, can you reproduce this issue in any other workspace?

**Comment by SimonHounsell** [comment] 2020-01-07 14:28
Hmm strange. Yes, other colleagues are experiencing the same issue and I'm also seeing the same issue on my personal laptop.

**Comment by kisstkondoros** [comment] 2020-04-20 21:15
I'm closing this in the best hope that it was eventually solved for you in some way (sorry).
If you could give me a reproducible example, I'll investigate further.

**Closed by kisstkondoros** 2020-04-20 21:15 UTC
