### ISSUE TITLE
[Feature Request] Take Angular/React/VUE template event binding reference as reference count.

### ISSUE THREAD

**Issue by x-strong** [kisstkondoros/typelens#56] opened 2020-08-06 02:43 UTC
Take Angular/React/VUE template event binding reference as reference count.

for example

<input type="button" value="check" (click)="check()" />

1 reference
function check():void{/*...*/}

**Comment by kisstkondoros** [comment] 2020-08-07 23:53
Thanks for reaching out!

The extension builds on top of standard vscode API's, and hence, this is something which should be provided by the language / framwork extensions, therefore I have no plans in implementing any special support for them.

This is more or less a duplicate of the following issues:
#6 #22 #25 #29

**Closed by kisstkondoros** 2020-08-07 23:53 UTC

**Comment by jerone** [comment] 2020-12-14 17:12
I came here to suggest the same, and understand that currently that's not possible yet.

It does look like they soon will prioritize the implementation into Angular Language Service: https://github.com/angular/vscode-ng-language-service/issues/29 🤞

**Comment by jerone** [comment] 2022-08-24 21:59
Can we re-open / re-think about this feature. 
It looks like the feature is implemented: https://github.com/angular/vscode-ng-language-service/issues/29#issuecomment-765598694
