### ISSUE TITLE
Extension breaks syntax highlighting

### ISSUE THREAD

**Issue by orokanasaru** [kisstkondoros/typelens#45] opened 2019-08-26 19:10 UTC
Without extension:

![image](https://user-images.githubusercontent.com/5751627/63716016-dd97ad80-c7f9-11e9-9a45-cfcbd2027e21.png)

With extension:

![image](https://user-images.githubusercontent.com/5751627/63715969-bfca4880-c7f9-11e9-8c3b-18e7cb163bbe.png)

It appears to grey out everything in an arrow function attached to module.exports, but traditional functions have no issues there.

There also seems to be some timing issue, as everything starts out highlighted correctly before turning grey. Occasionally, the colors are not broken, but they usually are.

**Comment by kisstkondoros** [comment] 2019-08-28 05:14
@orokanasaru I suppose there is some additional syntax highlighting related plugin ( [rainbow-brackets](https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets) potentially?), if so there is not much I could do with this as there is no way to synchronize the decorations between extensions AFAIK.

@wallsmetalroofing that is a separate issue, but I'll look into it

**Comment by kisstkondoros** [comment] 2019-08-28 05:27
@orokanasaru I'll close this as wontfix for now, as I can't really do a thing with it.
@wallsmetalroofing please upgrade to typelens@1.9.2 and report a separate issue with a full example code (based on the screenshot I couldn't reproduce it)

**Closed by kisstkondoros** 2019-08-28 05:27 UTC
